/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '8/14/19, 8:02 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-754.6.3.el6.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36' 
 * Generated on web client 'http://localhost:10080/SASStudio/38/main?locale=en_US&zone=GMT-06%253A00&http%3A%2F%2Flocalhost%3A10080%2FSASStudio%2F38%2Findex=' 
 *
 */

options validvarname=any;
ods noproctitle;
ods graphics / imagemap=on;

proc sort data=MIS480L.DATA out=WORK.TempSorted4877;
	by procedure_condition;
run;

proc boxplot data=WORK.TempSorted4877;
	plot (risk_adjusted_mortality_rate)*procedure_condition / boxstyle=schematic;
run;

proc datasets library=WORK noprint;
	delete TempSorted4877;
	run;
	
proc means data=MIS480L.DATA chartype mean std min max n vardef=df noprint;
	var risk_adjusted_mortality_rate;
	class procedure_condition;
	output out=work.Means_stats0003 mean=std=min=max=n= / autoname;
run;

proc sort data=work.Means_stats0003; 
  by descending risk_adjusted_mortality_r_Mean;
run;

proc print data=work.Means_stats0003;run;